version: '3.8'

services:
  # Node.js service
  node:
    build: .  # Construye la imagen desde el directorio actual
    ports:
      - "4500:4500"  # Ajusta el puerto si es necesario
    volumes:
      - ./your-app:/app  # Reemplaza 'your-app' con el directorio de tu aplicación
      - node-modules:/app/node_modules  # Volumen para el directorio node_modules
    working_dir: /app
    command: ["npm", "install"]  # Ejecuta npm install al iniciar el contenedor
    entrypoint: ["npm", "start"]  # Ejecuta el comando de inicio de tu aplicación

  # MySQL service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root  # Cambia la contraseña predeterminada
      MYSQL_DATABASE: prueba  # Cambia el nombre de la base de datos
    volumes:
      - mysql-data:/var/lib/mysql  # Volumen para persistir datos de MySQL

  # PostgreSQL service
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres  # Cambia la contraseña predeterminada
      POSTGRES_DB: prueba  # Cambia el nombre de la base de datos
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Volumen para persistir datos de PostgreSQL

  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/prueba  # Volumen para persistir datos de MongoDB

  # phpMyAdmin service (para administrar MySQL)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"  # Ajusta el puerto si es necesario
    environment:
      PMA_HOST: mysql
      PMA_USER: root  # Cambia el usuario si es necesario
      PMA_PASSWORD: root  # Cambia la contraseña si es necesario
    depends_on:
      - mysql  # phpMyAdmin necesita que MySQL esté disponible primero

# Volúmenes para persistir datos (opcional)
volumes:
  mysql-data: {}
  postgres-data: {}
  mongo-data: {}
  node-modules: {}

